# Generated by Django 5.2.1 on 2025-05-28 15:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Mô tả SEO'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Mô tả SEO'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Nội dung chi tiết bài viết'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag'),
        ),
    ]
