# Generated by Django 5.2.1 on 2025-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Tên website')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=255, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords')),
                ('tags', models.CharField(blank=True, help_text='Nhập các từ khóa, phân cách bằng dấu phẩy', max_length=500)),
                ('google_analytics_code', models.TextField(blank=True, help_text='Dán toàn bộ mã script Analytics', verbose_name='Google Analytics Code')),
                ('google_search_console_code', models.TextField(blank=True, help_text='Dán toàn bộ meta tag xác minh', verbose_name='Google Search Console Code')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt website',
                'verbose_name_plural': 'Cài đặt website',
            },
        ),
    ]
