# Generated by Django 5.2.1 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepage',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
    ]
