# Generated by Django 5.2.1 on 2025-05-27 19:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_singlepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepage',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Nội dung'),
        ),
    ]
