# Generated by Django 5.2.1 on 2025-05-28 15:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_singlepage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlepage',
            options={'verbose_name': 'Bài viết đơn lẻ', 'verbose_name_plural': 'Bài viết đơn lẻ'},
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
