# Generated by Django 5.2.1 on 2025-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfig',
            name='auto_reply_delay',
            field=models.PositiveIntegerField(default=30, verbose_name='Thời gian chờ trả lời tự động (giây)'),
        ),
        migrations.AddField(
            model_name='chatconfig',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật trả lời tự động'),
        ),
        migrations.AddField(
            model_name='chatconfig',
            name='auto_reply_message',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung trả lời tự động'),
        ),
    ]
