# Generated by Django 5.2.1 on 2025-05-28 15:59

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_tags_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Tên website')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=255, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords')),
                ('tags', models.CharField(blank=True, help_text='Nhập các từ khóa, phân cách bằng dấu phẩy', max_length=500)),
                ('google_analytics_code', models.TextField(blank=True, help_text='Dán toàn bộ mã script Analytics', verbose_name='Google Analytics Code')),
                ('google_search_console_code', models.TextField(blank=True, help_text='Dán toàn bộ meta tag xác minh', verbose_name='Google Search Console Code')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt website',
                'verbose_name_plural': 'Cài đặt website',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_id_a08e3c_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Hiển thị trang chủ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='accessory_for', to='products.product', verbose_name='Sản phẩm bán kèm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_night_vision',
            field=models.BooleanField(default=False, verbose_name='Có hồng ngoại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Có Wifi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_waterproof',
            field=models.BooleanField(default=False, verbose_name='Chống nước'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
