# Generated by Django 5.2.1 on 2025-05-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sitesetting_alter_product_options_and_more'),
    ]

    operations = [
    ]
